# Generated by Django 6.0.2 on 2026-02-11 08:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_reusable_blocks", "0005_add_head_injection_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reusableblock",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("raw_html", 1),
                    ("reusable_block", 2),
                    ("head_injection", 3),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail_reusable_blocks.models.reusable_block._ContentHTMLBlock",
                        (),
                        {},
                    ),
                    2: (
                        "wagtail_reusable_blocks.models.reusable_block._ReusableBlockChooserBlock",
                        (),
                        {},
                    ),
                    3: (
                        "wagtail_reusable_blocks.models.reusable_block._HeadInjectionBlock",
                        (),
                        {},
                    ),
                },
                help_text="The content of this reusable block",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="reusableblock",
            name="name",
            field=models.CharField(
                help_text="Human-readable name for this reusable block",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="reusableblock",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier, auto-generated from name",
                max_length=255,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
